### ISSUE TITLE
Roundtrip failure with multibyte characters

### ISSUE THREAD

**Issue by miniBill** [MartinSStewart/elm-codec-bytes#1]
A string like "Atlas de Sôtesburg" will not roundtrip. This is caused by `String.length` not giving the number of bytes but giving the number of characters. You can fix it (but it's a breaking change for non-ASCII text!) by changing the definition to:

```
{-| `Codec` between a sequence of bytes and an Elm `String`
-}
string : Codec String
string =
    map String.fromList String.toList <| list char

{-| `Codec` between a sequence of bytes and an Elm `Char`
-}
char : Codec Char
char =
    map Char.fromCode Char.toCode unsignedIntVar
```

Where `unsignedIntVar` is a variable length `Int`, like

```
unsignedIntVarEncoder : Int -> Encoder
unsignedIntVarEncoder =
    let
        toList i =
            if i < 128 then
                [ i ]

            else
                (128 + modBy 128 i) :: (toList <| i // 128)
    in
    BE.sequence << List.map BE.unsignedInt8 << toList


unsignedIntVarDecoder : Decoder Int
unsignedIntVarDecoder =
    BD.unsignedInt8
        |> BD.andThen
            (\h ->
                if h < 128 then
                    BD.succeed h

                else
                    BD.map (\ti -> (h - 128) + 128 * ti) unsignedIntVarDecoder
            )


{-| `Codec` between a signed variable-length integer and an Elm `Int`.
-}
unsignedIntVar : Codec Int
unsignedIntVar =
    build unsignedIntVarEncoder unsignedIntVarDecoder
```

Another option would be converting the string to `Bytes` immediately and using `Bytes.width`.

**Comment by MartinSStewart** [comment]
I'm sorry, I didn't get a notification for this issue! I'll take a look at your pull request now

**Comment by MartinSStewart** [comment]
I've published a fix now. `You can fix it (but it's a breaking change for non-ASCII text!) by changing the definition to: ...` I went ahead and took this approach. Since the previous behavior was already broken, I don't see an issue with a breaking change here.

Thanks for the issue, sorry about the delay!
